export const STUDENT_REPOSITORY = Symbol('STUDENT_REPOSITORY');
export const CLASS_REPOSITORY = Symbol('CLASS_REPOSITORY');
export const RATING_REPOSITORY = Symbol('RATING_REPOSITORY');
export const SEMESTER_REPOSITORY = Symbol('SEMESTER_REPOSITORY');
export const WORKER_REPOSITORY = Symbol('WORKER_REPOSITORY');
